const policies={
"الموارد البشرية":[["سياسة الحضور والانصراف","تنظيم أوقات العمل والحضور والانصراف والتأخير وفق أنظمة الشركة."],["سياسة الإجازات","تنظيم طلبات الإجازات والموافقات والأرصدة وآلية التوثيق."],["إجراءات التوظيف","مراحل طلب الشاغر والفرز والمقابلات والاعتماد وإتمام التعيين."],["إجراء تقييم الأداء","آلية تقييم أداء الموظفين وتحديد الأهداف وخطط التطوير."]],
"تقنية المعلومات":[["سياسة أمن المعلومات","حماية حسابات المستخدمين والأجهزة والبيانات ومنع الوصول غير المصرح به."],["سياسة كلمات المرور","متطلبات إنشاء كلمات المرور وتغييرها وحماية بيانات الدخول."],["إجراءات الدعم الفني","استقبال البلاغات وتصنيفها ومعالجتها وتصعيدها وإغلاقها."],["إجراءات إدارة الأجهزة","تسجيل الأجهزة وتهيئتها وتحديثها ومتابعة حالتها وصلاحياتها."]],
"التسويق والمبيعات":[["سياسة إدارة العملاء","تنظيم بيانات العملاء وآلية التعامل معها ومتابعة الفرص التجارية."],["سياسة العروض والمبيعات","ضوابط إعداد العروض والأسعار واعتمادها قبل تقديمها للعملاء."],["إجراءات متابعة العملاء","تسجيل التواصل والفرص ومراحل البيع ومتابعة النتائج."],["إجراءات الحملات التسويقية","تخطيط الحملات واعتماد المحتوى وقياس النتائج."]],
"المالية":[["سياسة المصروفات","ضوابط طلب المصروفات والموافقات والمستندات المؤيدة للصرف."],["سياسة العهد المالية","تنظيم العهد وتسليمها وتسويتها وإقفالها."],["إجراءات الفواتير","استلام الفواتير ومراجعتها واعتمادها وتسجيلها ومتابعة السداد."],["إجراءات إعداد التقارير","تنظيم إعداد التقارير المالية الدورية ومراجعتها واعتمادها."]],
"المشتريات":[["سياسة المشتريات","تنظيم طلبات الشراء والمنافسة واختيار الموردين والاعتماد."],["سياسة الموردين","ضوابط تقييم واعتماد الموردين ومتابعة أدائهم."],["إجراءات طلب شراء","إنشاء طلب الشراء والموافقات وتحويله إلى أمر شراء."],["إجراءات استلام التوريدات","مطابقة الأصناف والكميات والمستندات وتوثيق الاستلام."]]
};
const people={
"الموارد البشرية":[["مدير الموارد البشرية","مدير الإدارة"],["أخصائي موارد بشرية","الموارد البشرية"],["منسق توظيف","الموارد البشرية"]],
"تقنية المعلومات":[["مدير تقنية المعلومات","مدير الإدارة"],["مهندس تقنية معلومات","الدعم والبنية التحتية"],["أخصائي دعم فني","الدعم الفني"]],
"التسويق والمبيعات":[["مدير التسويق والمبيعات","مدير الإدارة"],["أخصائي تسويق","التسويق"],["مسؤول مبيعات","المبيعات"]],
"المالية":[["المدير المالي","مدير الإدارة"],["محاسب مالي","المحاسبة"],["أخصائي حسابات","الحسابات"]],
"المشتريات":[["مدير المشتريات","مدير الإدارة"],["أخصائي مشتريات","المشتريات"],["منسق موردين","المشتريات"]]
};
const input=document.getElementById("searchInput"),clear=document.getElementById("clearSearch"),cards=[...document.querySelectorAll(".department-card")],empty=document.getElementById("emptyState"),modal=document.getElementById("modal"),title=document.getElementById("modalTitle"),body=document.getElementById("modalBody");
document.getElementById("year").textContent=new Date().getFullYear();
const norm=x=>x.toLowerCase().trim().replace(/[إأآ]/g,"ا").replace(/ة/g,"ه");
function doSearch(){const q=norm(input.value);let n=0;cards.forEach(c=>{const ok=!q||norm(c.dataset.search+" "+c.innerText).includes(q);c.hidden=!ok;if(ok)n++});empty.hidden=n!==0;clear.hidden=!input.value}
input.addEventListener("input",doSearch);clear.addEventListener("click",()=>{input.value="";doSearch();input.focus()});
function openModal(dept,type){title.textContent=dept;if(type==="policy"){body.innerHTML='<div class="content-list">'+policies[dept].map(x=>`<div class="content-item"><strong>📋 ${x[0]}</strong><p>${x[1]}</p></div>`).join("")+"</div>"}else if(type==="people"){body.innerHTML='<div class="people-grid">'+people[dept].map(x=>`<div class="person"><b>♙ ${x[0]}</b><small>${x[1]}</small></div>`).join("")+"</div>"}else{body.innerHTML=`<div class="content-list"><div class="content-item"><strong>📋 السياسات والإجراءات</strong><p>تمت إضافة سياسات وإجراءات تجريبية للإدارة، ويمكن استبدالها بمحتوى الشركة لاحقًا.</p></div><div class="content-item"><strong>♙ المدراء والموظفون</strong><p>يمكن إضافة بيانات الموظفين والمديرين وصورهم ووسائل التواصل في المرحلة القادمة.</p></div></div>`}modal.hidden=false;document.body.style.overflow="hidden"}
document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openModal(b.dataset.dept,b.dataset.open));
document.querySelectorAll(".enter-btn").forEach(b=>b.onclick=()=>openModal(b.dataset.dept,"all"));
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{modal.hidden=true;document.body.style.overflow=""});
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.hidden){modal.hidden=true;document.body.style.overflow=""}});
document.querySelectorAll(".job-btn").forEach(b=>b.onclick=()=>{title.textContent=b.dataset.job;body.innerHTML=`<div class="content-list"><div class="content-item"><strong>نبذة عن الوظيفة</strong><p>فرصة وظيفية ضمن شركة عبدالرحمن الصاعدي. سيتم تحديث الوصف والمتطلبات وبيانات التقديم لاحقًا.</p></div><div class="content-item"><strong>متطلبات مبدئية</strong><p>مؤهل مناسب، مهارات مرتبطة بالوظيفة، والقدرة على العمل ضمن فريق.</p></div><button class="enter-btn" style="margin-top:12px">التقديم على الوظيفة</button></div>`;modal.hidden=false;document.body.style.overflow="hidden"});
document.querySelector(".cv-btn").onclick=()=>{title.textContent="إرسال السيرة الذاتية";body.innerHTML='<div class="content-item"><strong>التقديم العام</strong><p>هذه واجهة مبدئية. سيتم ربطها لاحقًا بنموذج رفع السيرة الذاتية والبريد أو قاعدة البيانات.</p></div>';modal.hidden=false;document.body.style.overflow="hidden"};
